mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zzwzzw
    url: jdbc:mysql://43.138.121.194:3306/exam?useSSl=false
server:
  port: 8999