mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd13579
    url: jdbc:mysql://localhost:3306/exam?useSSl=false
server:
  port: 8999